### ISSUE TITLE
全局validator

### ISSUE THREAD

**Issue by Duan-fei** [smokezl/govalidators#1]
我想定义一个全局validator，但是目前你的goValidator是一个私有的，能否更改一下这一块呢

**Comment by smokezl** [comment]
validator := govalidators.New()
可以将这个 validator 变为全局变量，可以满足么？

**Comment by smokezl** [comment]
> 我想定义一个全局validator，但是目前你的goValidator是一个私有的，能否更改一下这一块呢

validator := govalidators.New()
可以将这个 validator 变为全局变量，可以满足么？
