### ISSUE TITLE
在高并发情况下不能准确验证

### ISSUE THREAD

**Issue by yk133** [smokezl/govalidators#2]
在高并发情况下不能准确验证，
相同的请求，大约在单机1wqps时，会出现一两百的验证不通过，
报错是验证器出错，麻烦看一下是什么问题导致的？
粗看了一下剩余内存是很多的

**Comment by smokezl** [comment]
可以查到是哪个验证报错么？方便把错误截图下么？我这边查看下

**Comment by yk133** [comment]
XXX int64 `"json:"XXX" validate:"integer=0,_"`
XXX validator range error 保证输入的结构体 Tag都是正确的，大约两万次请求出现7-8次
XXX就是那个验证的字段，
如果是字符串验证长度的时候是[1,100] 也会出现，它说长度至少应该是1 ，但是我给的是“1234”
Go环境1.13.5
linux

**Comment by smokezl** [comment]
好的，这周我测试修复一下

**Comment by yk133** [comment]
Hi
有查到问题吗

**Comment by smokezl** [comment]
不好意思，还没有呢，最近工作比较忙～清明假期，我修复下哈

**Comment by smokezl** [comment]
hi~你是创建的全局的 validator 是吧？
而不是每次请求的时候单独 validator := New() 来创建

**Comment by smokezl** [comment]
> Hi
> 有查到问题吗

问题已经定位，清明假期过完之前会修复

**Comment by smokezl** [comment]
> Hi
> 有查到问题吗

已经修复

**Comment by yk133** [comment]
是的，我是通过创建全局变量来每次使用的

**Comment by smokezl** [comment]
已经修复了

**Comment by yk133** [comment]
好的，是并发导致的吗？

**Comment by smokezl** [comment]
是的，全局的话，每个验证器结构体用的都是同一个，并发的时候，会造成新数据把老数据覆盖
