### ISSUE TITLE
报错信息修改为中文，输出的还是英文

### ISSUE THREAD

**Issue by lnb-wxqy** [smokezl/govalidators#6]
大佬好，试了简书的例子（地址：https://www.jianshu.com/p/64757be312a4），发现报错信息修改为中文后，输出的还是英文，跟了下源码，发现如下问题：
` if vT.Kind() == reflect.Ptr {
				// defaultValidator 传的结构体指针，在并发条件下，会导致结构体值被覆盖，需要做对象拷贝
				baseValidator := reflect.New(vV.Elem().Type()).Interface()
				validator = baseValidator.(Validator)
				params.structValidator[vK] = validator
			}`
此处对象拷贝时，只拷贝了类型没有拷贝属性值，导致报错信息输出的还是英文。
尝试做了一下修改后，中文可以输出。大佬有空的话麻烦瞅瞅别，菜鸟一枚，提的不对的话还请包涵，嘻嘻！
`if vT.Kind() == reflect.Ptr {
				// defaultValidator 传的结构体指针，在并发条件下，会导致结构体值被覆盖，需要做对象拷贝
				//baseValidator := reflect.New(vV.Elem().Type()).Interface()
				//TODO 修改
				baseValidator :=reflect.New(vV.Elem().Type())
				baseValidator.Elem().Set(vV.Elem())
				validator = baseValidator.Interface().(Validator)
				//validator = baseValidator.(Validator)
				params.structValidator[vK] = validator
			}`

**Comment by smokezl** [comment]
好的，这几天有空，我看一下哈

**Comment by smokezl** [comment]
已经修复，就是这里的问题，感谢
